### ISSUE TITLE
实现垂直居中显示

### ISSUE THREAD

**Issue by Hzhxi9** [Hzhxi9/js-learn#5]
1.  绝对定位 + translate
```css
.parent{
  position: relative;
}
.children{
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}
```

2. 绝对定位
```css
.parent{
  position: relative;
}
.children{
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  margin: auto;
}
```
3. 绝对定位 + margin
```css
.parent{
  position: relative;
}
.children{
  position: absolute;
  top: 50%;
  left: 50%;
  margin-left:  -50px;  /*自身height 的一半**/
  margin-top: -50px;  /*自身width的一半**/
}
```
4. flex 布局
```css
.parent{
  display: flex;
  jusity-content: center;
 align-items: center;
}
```
